import { useState } from "react";
import { Link } from "react-router-dom";
import {
  BrainCircuit,
  ArrowLeft,
  Play,
  CheckCircle,
  Loader2,
} from "lucide-react";

function AIInterview() {
  const [role, setRole] = useState("Software Engineer");
  const [interviewType, setInterviewType] = useState("Technical");
  const [difficulty, setDifficulty] = useState("Medium");
  const [questionCount, setQuestionCount] = useState("10");

  const [questions, setQuestions] = useState([]);
  const [answers, setAnswers] = useState([]);
  const [evaluations, setEvaluations] = useState([]);

  const [started, setStarted] = useState(false);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [answer, setAnswer] = useState("");

  const [score, setScore] = useState(null);
  const [feedback, setFeedback] = useState("");
  const [strengths, setStrengths] = useState([]);
  const [improvements, setImprovements] = useState([]);

  const [completed, setCompleted] = useState(false);
  const [loading, setLoading] = useState(false);

  // ==========================================
  // START INTERVIEW
  // ==========================================

   const startInterview = async () => {
  setLoading(true);

  try {
    const response = await fetch(
      "http://localhost:5000/api/start-interview",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          role,
          interviewType,
          difficulty,
          questionCount: Number(questionCount),
        }),
      }
    );

    const data = await response.json();

    if (!response.ok || !data.success) {
      throw new Error(
        data.message || "Failed to generate interview questions."
      );
    }

    console.log("All AI Questions:", data.questions);

    // Store ALL questions at once
    setQuestions(data.questions);

    // Reset interview
    setAnswers([]);
    setEvaluations([]);
    setCurrentQuestion(0);
    setAnswer("");
    setScore(null);
    setFeedback("");
    setStrengths([]);
    setImprovements([]);
    setCompleted(false);

    setStarted(true);
  } catch (error) {
    console.error("Start Interview Error:", error);

    alert(
      error.message ||
        "Unable to generate interview questions."
    );
  } finally {
    setLoading(false);
  }
};

   

  // ==========================================
  // SUBMIT ANSWER FOR AI EVALUATION
  // ==========================================

  const submitAnswer = async () => {
    if (!answer.trim()) {
      alert("Please enter your answer before submitting.");
      return;
    }

    setLoading(true);

    try {
      const response = await fetch(
        "http://localhost:5000/api/evaluate-answer",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            role,
            interviewType,
            difficulty,
            question: questions[currentQuestion],
            answer,
          }),
        }
      );

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.message || "Failed to evaluate answer.");
      }

      setScore(data.score);
      setFeedback(data.feedback || "");
      setStrengths(data.strengths || []);
      setImprovements(data.improvements || []);

      setAnswers((previousAnswers) => [
        ...previousAnswers,
        answer,
      ]);

      setEvaluations((previousEvaluations) => [
        ...previousEvaluations,
        data,
      ]);
    } catch (error) {
      console.error("Evaluation Error:", error);
      alert(error.message || "Unable to evaluate your answer.");
    } finally {
      setLoading(false);
    }
  };

  // ==========================================
  // NEXT QUESTION / FINISH
  // ==========================================

   const nextQuestion = () => {
  if (currentQuestion >= Number(questionCount) - 1) {
    setCompleted(true);
    return;
  }

  // Move to the next question already generated by Gemini
  setCurrentQuestion((previous) => previous + 1);

  setAnswer("");
  setScore(null);
  setFeedback("");
  setStrengths([]);
  setImprovements([]);
};

  // ==========================================
  // RESET INTERVIEW
  // ==========================================

  const resetInterview = () => {
    setStarted(false);
    setQuestions([]);
    setAnswers([]);
    setEvaluations([]);
    setCurrentQuestion(0);
    setAnswer("");
    setScore(null);
    setFeedback("");
    setStrengths([]);
    setImprovements([]);
    setCompleted(false);
  };

  // ==========================================
  // FINAL SCORE
  // ==========================================

  const finalScore =
    evaluations.length > 0
      ? Math.round(
          evaluations.reduce(
            (total, item) => total + Number(item.score || 0),
            0
          ) / evaluations.length
        )
      : 0;

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-white transition-colors duration-300">

      {/* Navbar */}
      <nav className="bg-white dark:bg-slate-900 border-b border-gray-200 dark:border-slate-800 px-6 py-4">
        <div className="max-w-6xl mx-auto flex items-center justify-between">

          <Link
            to="/dashboard"
            className="text-2xl font-bold text-cyan-500"
          >
            IntelliPrep-AI
          </Link>

          <Link
            to="/dashboard"
            className="flex items-center gap-2 text-gray-600 dark:text-gray-300 hover:text-cyan-500 transition"
          >
            <ArrowLeft size={18} />
            Dashboard
          </Link>

        </div>
      </nav>

      {/* Main Content */}
      <main className="max-w-5xl mx-auto px-6 py-12">

        {/* Header */}
        <div className="text-center mb-10">

          <div className="flex justify-center mb-5">
            <div className="p-5 rounded-2xl bg-cyan-500/10 text-cyan-500">
              <BrainCircuit size={48} />
            </div>
          </div>

          <h1 className="text-4xl md:text-5xl font-bold">
            AI Interview
          </h1>

          <p className="text-gray-600 dark:text-gray-400 mt-4 max-w-2xl mx-auto leading-7">
            Practice realistic interview questions and improve your
            performance with AI-powered feedback.
          </p>

        </div>

        {/* ==========================================
            INTERVIEW SETUP
        ========================================== */}

        {!started && !completed && (
          <div className="bg-white dark:bg-slate-900 rounded-3xl shadow-xl border border-gray-200 dark:border-slate-800 p-8 md:p-10">

            <h2 className="text-2xl font-bold mb-8">
              Set Up Your Mock Interview
            </h2>

            <div className="grid md:grid-cols-2 gap-6">

              {/* Job Role */}
              <div>
                <label className="block mb-2 font-semibold">
                  Job Role
                </label>

                <select
                  value={role}
                  onChange={(e) => setRole(e.target.value)}
                  className="w-full p-4 rounded-xl bg-slate-100 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 outline-none focus:ring-2 focus:ring-cyan-500"
                >
                  <option>Software Engineer</option>
                  <option>Frontend Developer</option>
                  <option>Backend Developer</option>
                  <option>Data Analyst</option>
                  <option>Full Stack Developer</option>
                </select>
              </div>

              {/* Interview Type */}
              <div>
                <label className="block mb-2 font-semibold">
                  Interview Type
                </label>

                <select
                  value={interviewType}
                  onChange={(e) => setInterviewType(e.target.value)}
                  className="w-full p-4 rounded-xl bg-slate-100 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 outline-none focus:ring-2 focus:ring-cyan-500"
                >
                  <option>Technical</option>
                  <option>HR</option>
                  <option>Mixed</option>
                </select>
              </div>

              {/* Difficulty */}
              <div>
                <label className="block mb-2 font-semibold">
                  Difficulty
                </label>

                <select
                  value={difficulty}
                  onChange={(e) => setDifficulty(e.target.value)}
                  className="w-full p-4 rounded-xl bg-slate-100 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 outline-none focus:ring-2 focus:ring-cyan-500"
                >
                  <option>Easy</option>
                  <option>Medium</option>
                  <option>Hard</option>
                </select>
              </div>

              {/* Question Count */}
              <div>
                <label className="block mb-2 font-semibold">
                  Number of Questions
                </label>

                <select
                  value={questionCount}
                  onChange={(e) => setQuestionCount(e.target.value)}
                  className="w-full p-4 rounded-xl bg-slate-100 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 outline-none focus:ring-2 focus:ring-cyan-500"
                >
                  <option value="5">5 Questions</option>
                  <option value="10">10 Questions</option>
                  <option value="15">15 Questions</option>
                </select>
              </div>

            </div>

            {/* Selected Settings */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-8">

              <div className="p-4 rounded-xl bg-cyan-500/10">
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Role
                </p>
                <p className="font-semibold mt-1">{role}</p>
              </div>

              <div className="p-4 rounded-xl bg-cyan-500/10">
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Type
                </p>
                <p className="font-semibold mt-1">
                  {interviewType}
                </p>
              </div>

              <div className="p-4 rounded-xl bg-cyan-500/10">
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Difficulty
                </p>
                <p className="font-semibold mt-1">
                  {difficulty}
                </p>
              </div>

              <div className="p-4 rounded-xl bg-cyan-500/10">
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Questions
                </p>
                <p className="font-semibold mt-1">
                  {questionCount}
                </p>
              </div>

            </div>

            {/* Start Button */}
            <button
              onClick={startInterview}
              disabled={loading}
              className="w-full mt-8 flex items-center justify-center gap-2 bg-cyan-500 hover:bg-cyan-600 disabled:opacity-60 disabled:cursor-not-allowed text-white px-8 py-4 rounded-xl font-semibold transition"
            >
              {loading ? (
                <>
                  <Loader2 size={20} className="animate-spin" />
                  Generating Questions...
                </>
              ) : (
                <>
                  <Play size={20} />
                  Start Interview
                </>
              )}
            </button>

          </div>
        )}

        {/* ==========================================
            INTERVIEW
        ========================================== */}

        {started && !completed && (
          <div className="bg-white dark:bg-slate-900 rounded-3xl shadow-xl border border-gray-200 dark:border-slate-800 p-8 md:p-10">

            {/* Interview Information */}
            <div className="flex flex-wrap gap-3 mb-6">

              <span className="px-4 py-2 rounded-full bg-cyan-500/10 text-cyan-500 text-sm font-semibold">
                {role}
              </span>

              <span className="px-4 py-2 rounded-full bg-cyan-500/10 text-cyan-500 text-sm font-semibold">
                {interviewType}
              </span>

              <span className="px-4 py-2 rounded-full bg-cyan-500/10 text-cyan-500 text-sm font-semibold">
                {difficulty}
              </span>

            </div>

            {/* Progress */}
            <div className="flex justify-between items-center mb-6">

              <p className="text-sm text-gray-500 dark:text-gray-400">
                Question {currentQuestion + 1} of {questionCount}
              </p>

              <p className="text-sm font-semibold text-cyan-500">
                {Math.round(
                  ((currentQuestion + 1) / Number(questionCount)) * 100
                )}
                %
              </p>

            </div>

            {/* Progress Bar */}
            <div className="w-full h-2 bg-gray-200 dark:bg-slate-800 rounded-full mb-8">
              <div
                className="h-2 bg-cyan-500 rounded-full transition-all duration-300"
                style={{
                  width: `${
                    ((currentQuestion + 1) / Number(questionCount)) * 100
                  }%`,
                }}
              />
            </div>

            {/* Question */}
            <h2 className="text-2xl font-bold leading-8 mb-6">
              {questions[currentQuestion]}
            </h2>

            {/* Answer */}
            <textarea
              value={answer}
              onChange={(e) => setAnswer(e.target.value)}
              rows="8"
              placeholder="Type your answer here..."
              disabled={score !== null || loading}
              className="w-full p-5 rounded-xl bg-slate-100 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 outline-none focus:ring-2 focus:ring-cyan-500 resize-none disabled:opacity-70"
            />

            {/* Submit */}
            {score === null && (
              <button
                onClick={submitAnswer}
                disabled={loading}
                className="mt-6 flex items-center gap-2 bg-cyan-500 hover:bg-cyan-600 disabled:opacity-60 text-white px-7 py-3 rounded-xl font-semibold transition"
              >
                {loading ? (
                  <>
                    <Loader2 size={18} className="animate-spin" />
                    AI Evaluating...
                  </>
                ) : (
                  "Submit Answer"
                )}
              </button>
            )}

            {/* AI Feedback */}
            {score !== null && (
              <div className="mt-8">

                <div className="bg-cyan-500/10 border border-cyan-500/20 rounded-2xl p-6">

                  <div className="flex items-center gap-3 mb-4">
                    <CheckCircle className="text-cyan-500" />

                    <h3 className="text-xl font-bold">
                      AI Answer Evaluation
                    </h3>
                  </div>

                  <p className="text-4xl font-bold text-cyan-500 mb-4">
                    {score}/10
                  </p>

                  <p className="text-gray-600 dark:text-gray-300 leading-7">
                    {feedback}
                  </p>

                  {strengths.length > 0 && (
                    <div className="mt-6">
                      <h4 className="font-bold mb-2">
                        Strengths
                      </h4>

                      <ul className="list-disc pl-5 space-y-1 text-gray-600 dark:text-gray-300">
                        {strengths.map((item, index) => (
                          <li key={index}>{item}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {improvements.length > 0 && (
                    <div className="mt-6">
                      <h4 className="font-bold mb-2">
                        Areas for Improvement
                      </h4>

                      <ul className="list-disc pl-5 space-y-1 text-gray-600 dark:text-gray-300">
                        {improvements.map((item, index) => (
                          <li key={index}>{item}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                </div>

                <button
                  onClick={nextQuestion}
                  disabled={loading}
                  className="mt-6 bg-cyan-500 hover:bg-cyan-600 disabled:opacity-60 text-white px-7 py-3 rounded-xl font-semibold transition"
                >
                  {currentQuestion === Number(questionCount) - 1
                    ? "Finish Interview"
                    : "Next Question"}
                </button>

              </div>
            )}

          </div>
        )}

        {/* ==========================================
    COMPLETED
========================================== */}

{completed && (
  <div className="bg-white dark:bg-slate-900 rounded-3xl shadow-xl border border-gray-200 dark:border-slate-800 p-8 md:p-10">

    {/* Header */}
    <div className="text-center">

      <div className="flex justify-center mb-6">
        <div className="p-5 rounded-full bg-green-500/10 text-green-500">
          <CheckCircle size={55} />
        </div>
      </div>

      <h2 className="text-4xl font-bold">
        Interview Completed 🎉
      </h2>

      <p className="text-gray-600 dark:text-gray-400 mt-4">
        Great job! Here is your IntelliPrep-AI interview performance.
      </p>

    </div>

    {/* Overall Score */}
    <div className="mt-10 bg-cyan-500/10 rounded-3xl p-8 text-center">

      <p className="text-gray-500 dark:text-gray-400">
        Overall Score
      </p>

      <p className="text-6xl font-extrabold text-cyan-500 mt-3">
        {finalScore}/10
      </p>

      <p className="mt-3 text-gray-600 dark:text-gray-400">
        Based on {evaluations.length} evaluated answers
      </p>

    </div>

    {/* Interview Details */}
    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-8">

      <div className="p-5 rounded-xl bg-slate-100 dark:bg-slate-800">
        <p className="text-sm text-gray-500 dark:text-gray-400">
          Role
        </p>

        <p className="font-semibold mt-2">
          {role}
        </p>
      </div>

      <div className="p-5 rounded-xl bg-slate-100 dark:bg-slate-800">
        <p className="text-sm text-gray-500 dark:text-gray-400">
          Type
        </p>

        <p className="font-semibold mt-2">
          {interviewType}
        </p>
      </div>

      <div className="p-5 rounded-xl bg-slate-100 dark:bg-slate-800">
        <p className="text-sm text-gray-500 dark:text-gray-400">
          Difficulty
        </p>

        <p className="font-semibold mt-2">
          {difficulty}
        </p>
      </div>

      <div className="p-5 rounded-xl bg-slate-100 dark:bg-slate-800">
        <p className="text-sm text-gray-500 dark:text-gray-400">
          Questions
        </p>

        <p className="font-semibold mt-2">
          {evaluations.length}
        </p>
      </div>

    </div>

    {/* Performance Message */}
    <div className="mt-8 p-6 rounded-2xl bg-slate-100 dark:bg-slate-800">

      <h3 className="text-xl font-bold mb-3">
        Performance Summary
      </h3>

      <p className="text-gray-600 dark:text-gray-300 leading-7">
        {finalScore >= 8
          ? "Excellent performance! Your answers demonstrate strong preparation and understanding."
          : finalScore >= 6
          ? "Good performance! You have a solid foundation, but there are still areas you can improve."
          : "Keep practicing! Focus on improving your technical knowledge, clarity, and confidence."}
      </p>

    </div>

    {/* Question-by-Question Scores */}
    {evaluations.length > 0 && (
      <div className="mt-8">

        <h3 className="text-2xl font-bold mb-5">
          Question Performance
        </h3>

        <div className="space-y-4">

          {evaluations.map((evaluation, index) => (
            <div
              key={index}
              className="flex items-center justify-between gap-4 p-5 rounded-xl bg-slate-100 dark:bg-slate-800"
            >

              <div>
                <p className="font-semibold">
                  Question {index + 1}
                </p>

                <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
                  {evaluation.feedback}
                </p>
              </div>

              <div className="text-xl font-bold text-cyan-500 whitespace-nowrap">
                {evaluation.score}/10
              </div>

            </div>
          ))}

        </div>

      </div>
    )}

    {/* Actions */}
    <div className="flex flex-col md:flex-row justify-center gap-4 mt-10">

      <button
        onClick={resetInterview}
        className="bg-cyan-500 hover:bg-cyan-600 text-white px-8 py-3 rounded-xl font-semibold transition"
      >
        🔄 Start New Interview
      </button>

      <Link
        to="/dashboard"
        className="border border-cyan-500 text-cyan-500 hover:bg-cyan-500 hover:text-white px-8 py-3 rounded-xl font-semibold text-center transition"
      >
        🏠 Back to Dashboard
      </Link>

    </div>

  </div>
)} 

      </main>
    </div>
  );
}

export default AIInterview;